### ISSUE TITLE
User Story 25: Save System

### ISSUE THREAD

**Issue by Caramajau** [Oskmey/-Agile-software-project-management#113]
# User Story 25
## Desc
As a gamer
I want to be able to save
So that I can keep my progress between game sessions.
## Acceptance criteria 
The game should be able to save and load game data. 
### Tasks
- [ ] Make the game be able to save money
- [ ] Make the game be able to save inverntory
- [ ] Make the game be able to save trash stats
