### ISSUE TITLE
User Story 5k: New Legendary Trash

### ISSUE THREAD

**Issue by Caramajau** [Oskmey/-Agile-software-project-management#119]
# User Story 5k
## Desc
As someone who is interested in learning more about the pollution of the oceans
I want many types of trash in the game and information about that trash
so that I can learn about what trash is polluting the ocean and how it affects it
## Acceptance criteria 
There should be a new legendary trash in the game and it has points/value as well as facts/info
### Tasks
- [ ] Add information about the trash.
- [ ] Add icon for the trash.
- [ ] Give the trash a legendary rarity
