### ISSUE TITLE
User story 7: Store

### ISSUE THREAD

**Issue by linuskar** [Oskmey/-Agile-software-project-management#12]
# Store
## User story 7
As a capitalist player
I want a store
so that I can spend my money to get things
## Acceptance criteria
- A shop exists where the player can spend its money to buy a thing
## Tasks
- [x] Create a shop interface
- [x] Create a way to access the store in the world
- [x] Be able to buy something from the store for money
# Estimate
8
