### ISSUE TITLE
User Story 31: Customisable controls

### ISSUE THREAD

**Issue by Caramajau** [Oskmey/-Agile-software-project-management#132]
# User Story 31
## Desc
As a gamer who likes customizability 
I want to be able to customise my controls
So that I can change them to fit my playstyle
## Acceptance criteria 
The player should be able to change all controls to hotkeys that they want. 
### Tasks
- [ ] Show controls in the settings menu
- [ ] Allow them to be changed in the settings menu
- [ ] If controls are still shown in the How to play screen, then they should also update when changing controls.
