### ISSUE TITLE
User story 8: Create a new level

### ISSUE THREAD

**Issue by AronLundh** [Oskmey/-Agile-software-project-management#14]
## User-stories 
As a gamer who likes progression
I want to be able to unlock different levels
so that I feel that the game has variety and progress

## Acceptance criteria
Add at least one more level 

## Tasks
- [ ] Create a map
- [ ] Create a new world
- [ ] A player should be able to travel between worlds
- [ ] A player should be able to buy the new world in the shop

## Estimate
13
