### ISSUE TITLE
User story 11: Create first world

### ISSUE THREAD

**Issue by HermanForsberg** [Oskmey/-Agile-software-project-management#17]
# Create first world

## User-stories 
As a player
I want to have a world where i can walk around and access all parts of the game
so that doing things in the game feels more immersive

## Acceptance criteria
- [x] Have a world where the player can walk around and access all the game's major features, like the store, recycling place and fishing.

## Task
- [x] Create a world where the player can walk around
- [x] Have a place in the world where the player can access the store
- [x] Have a place in the world where the player can recycle
- [x] Have a place in the world where the player can fish
- [x] Have textures for places that the player can interact with  

## Estimate
13
