### ISSUE TITLE
User story 14: First accessory

### ISSUE THREAD

**Issue by HermanForsberg** [Oskmey/-Agile-software-project-management#21]
# First accessory

## User-stories 
As a gamer who likes variety
I want an accessory in the game
so that the gameplay can have more variation
## Acceptance criteria
- [x] One working accessory which modifying the gameplay in some way. 

## Tasks
- [x] Create an accessory
- [x] Make the upgrades interactable

## Estimate
3
