### ISSUE TITLE
User story 15: More accessories

### ISSUE THREAD

**Issue by HermanForsberg** [Oskmey/-Agile-software-project-management#22]
# Another Accessories

## User-stories 
As a gamer who likes variety
I want accessories in the game
so that the gameplay can have more variation

## Acceptance criteria
- [x] Have another working accessories which modifies the gameplay in some way.

## Tasks
- [x] Create one more accessories
- [x] Make the accessories interactable

## Estimate
5
