### ISSUE TITLE
User story 3: Recycling

### ISSUE THREAD

**Issue by linuskar** [Oskmey/-Agile-software-project-management#3]
# Recycling

## User story 3
As a gaming climate activist 
I want to be able to recycle the trash
so that it can be used for better purposes. 
## Acceptance criteria
- The trash collected in the game can be recycled and you get money from it. 
## Tasks
- [x] Create a recycle machine
- [x] Create money system
- [x] Make the recycle machine accept trash when pressing a button
- [x] Make it generate money when trash is inserted. 

## Estimate:
3
