### ISSUE TITLE
User story 2: Trash implementation

### ISSUE THREAD

**Issue by Caramajau** [Oskmey/-Agile-software-project-management#4]
# Trash implementation

## User-story:
As an environmentalist gamer
I want trash in the game
so that i can be aware of the trash that exist

## Acceptance criteria: 
Trash exists in the game with it’s related information. 

## Tasks
- [x] Create one type of trash
- [x] Added trash information
- [x] Connect the two with each other
- [x] Create trash categories. 

Estimate: 3
