### ISSUE TITLE
User story 1: Fishing Minigame

### ISSUE THREAD

**Issue by HugoUnosson** [Oskmey/-Agile-software-project-management#5]
# Fishing Minigame

## User story 1 
As a fishing gamer
I want to be able to fish
so that I can experience the joy of fishing in the game

## Acceptance criteria
- [ ] Can fish one type of trash

## Tasks
- [ ] Add fishing system
- [x] Add one minigame
- [ ] Add functionality to support trash
- [ ] Add functionality to add multiple minigames

## Estimate:
3
