### ISSUE TITLE
User story 4: First sprint MVP

### ISSUE THREAD

**Issue by linuskar** [Oskmey/-Agile-software-project-management#6]
# First sprint MVP
## User story 4 
As an agile developer
I want a MVP for the first sprint
so that we have a product that is ready to launch
## Acceptance criteria
Connect the branches/features into a working MVP
## Tasks
- [ ] Add a simple counter to trash collected
- [ ] Recycling based on trash collected
- [ ] Fishing trash gets pop-up with fact info
- [ ] Create a Unity build for MVP
## Estimate
5
