### ISSUE TITLE
User story 5a: Cigarette butts

### ISSUE THREAD

**Issue by linuskar** [Oskmey/-Agile-software-project-management#7]
# Cigarette butts
## User story 5a
As someone who is interested in learning more about the pollution of the oceans
I want many types of trash in the game and information about that trash
so that I can learn about what trash is polluting the ocean and how it affects it
## Acceptance criteria
- Cigarette butt has points/value as well as facts/info
## Tasks
Tasks:
- [x] Add Information about Cigarette butts in the ocean
- [x] A spawn rate/rarity
- [x] Add icons for the cigarette butts
- [x] Cigarette butts

## Estimate
2
