### ISSUE TITLE
User story 5b: PET Bottle Trash

### ISSUE THREAD

**Issue by Caramajau** [Oskmey/-Agile-software-project-management#77]
# PET Bottle Trash
## User story 5b
As someone who is interested in learning more about the pollution of the oceans
I want many types of trash in the game and information about that trash
so that I can learn about what trash is polluting the ocean and how it affects it
## Acceptance criteria
- A new kind of trash exists, which is PET Bottles. 
## Tasks
Tasks:
- [x] Add Information about each PET bottle
- [x] A fishing spawn rates
- [x] Add icons to PET bottle
## Estimate
2
