### ISSUE TITLE
User story 5c: Electric Scooter Trash

### ISSUE THREAD

**Issue by HugoUnosson** [Oskmey/-Agile-software-project-management#78]
# Electric Scooter Trash
## User story 5c
As someone who is interested in learning more about the pollution of the oceans
I want many types of trash in the game and information about that trash
so that I can learn about what trash is polluting the ocean and how it affects it

## Acceptance criteria
- Electric scooter type trash exists and has different points/value as well as facts/info

## Tasks
Tasks:
- [ ] Add information about the trash
- [ ] Add a fishing spawn rates / rarity
- [ ] Add an icon to the trash 
- [ ] The trash type is an Electric scooter

## Estimate
2
