### ISSUE TITLE
User story 17: Fix MVP bugs

### ISSUE THREAD

**Issue by Caramajau** [Oskmey/-Agile-software-project-management#81]
## User-stories 
As a game developer 
I want a bug-free game
So that I can play the game without encountering bugs

## Acceptance criteria
The encountred issues in the MVP should be fixed

## Tasks
- [x] Being able to fish more than once
- [x] Having consistent controls across different devices (as well as same input system)
- [x] Having a structured project. 

## Estimate
5
