### ISSUE TITLE
User story 17: Add start screen

### ISSUE THREAD

**Issue by AronLundh** [Oskmey/-Agile-software-project-management#82]
# User Story 18
## Desc
As a experienced gamer 
I want a start screen
so that the games satisfies my expectations
## Acceptance criteria 
A start screen is added to the game, with a start, quit, how to play and options button
### Tasks
- [ ] Create a start screen
- [ ] Add start button
- [ ] Add quit button
- [ ] Add how to play button
- [ ] Add options button
