### ISSUE TITLE
User story 19: Pause Menu

### ISSUE THREAD

**Issue by HugoUnosson** [Oskmey/-Agile-software-project-management#84]
# User Story 19
## Desc
As a person who likes coffee 
I want to be able to pause the game
So that I can take coffee breaks whenever I want

## Acceptance criteria 
A clickable pause symbol that pauses the game.

### Tasks
- [x] Create a symbol for pause.
- [x] Make it clickable.
- [x] Make sure you can pause without destroying the rest of the game.
- [x] Make sure you can resume.
