### ISSUE TITLE
User story 6: Inventory

### ISSUE THREAD

**Issue by linuskar** [Oskmey/-Agile-software-project-management#9]
# Inventory
## User story 6
As a simulation-role-playing gamer
I want an inventory
so that I can see what trash I have collected.
## Acceptance criteria
- The inventory is able to store different kinds of trash with information, and the trash/inventory is interactable.
## Tasks
- [ ] Create inventory screen
- [ ] Make the inventory screen interactable
- [ ] Add ability to have trash icons in the screen. 
- [ ] Create item info window
## Estimate
13

**Comment by linuskar** [comment]
Trying to follow this inventory system: 
https://www.youtube.com/playlist?list=PLcRSafycjWFegXSGBBf4fqIKWkHDw_G8D

Trying to implement something for saving the inventory: 
https://www.youtube.com/playlist?list=PL3viUl9h9k7-tMGkSApPdu4hlUBagKial
