### ISSUE TITLE
User story 22: Animations for recycling

### ISSUE THREAD

**Issue by AronLundh** [Oskmey/-Agile-software-project-management#94]
# User Story 22
## Desc
As a graphic designer,
I want animations for recycling,
so that the game is more fun
## Acceptance criteria 
There should be an animation for recycling
### Tasks
- [x] Edit the sprite so that it recycles
- [x] Make the animations for recycling
- [ ] Connect the animations with recycling functionality
