### ISSUE TITLE
User Story 5f: Glass Bottle

### ISSUE THREAD

**Issue by Caramajau** [Oskmey/-Agile-software-project-management#95]
# User Story 5f
## Desc
As someone who is interested in learning more about the pollution of the oceans
I want many types of trash in the game and information about that trash
so that I can learn about what trash is polluting the ocean and how it affects it

## Acceptance criteria 
Glass bottle type trash exists and has different points/value as well as facts/info. 

### Tasks
- [x] Add information about the glass bottles in the ocean
- [x] Add a fishing spawn rate / rarity
- [x] Add an icon to the glass bottle
