### ISSUE TITLE
User story 5d: Car tire

### ISSUE THREAD

**Issue by HermanForsberg** [Oskmey/-Agile-software-project-management#96]
# User Story 5d
## Desc
As someone who is interested in learning more about the pollution of the oceans
I want many types of trash in the game and information about that trash
so that I can learn about what trash is polluting the ocean and how it affects it## Acceptance criteria 
Write here
## Acceptance criteria
* Car tire has points/value as well as facts/info
## Tasks
- [ ]  Add Information about Cigarette butts in the ocean
- [ ]  A spawn rate/rarity
- [ ]  Add icons for the cigarette butts

## Estimate
1
