### ISSUE TITLE
User Story 5e: Plastic Spoon Trash

### ISSUE THREAD

**Issue by HugoUnosson** [Oskmey/-Agile-software-project-management#97]
# Plastic Spoon Trash
## User Story 5e
As someone who is interested in learning more about the pollution of the oceans
I want many types of trash in the game and information about that trash
so that I can learn about what trash is polluting the ocean and how it affects it

## Acceptance criteria 
- Plastic spoon type trash exists and has different points/value as well as facts/info

## Tasks
- [x] Add information about plastic spoons in the ocean
- [x] A fishing spawn rate
- [x] Add icon for plastic spoon

## Estimate
2
