### ISSUE TITLE
User story 24: Credits screen

### ISSUE THREAD

**Issue by HermanForsberg** [Oskmey/-Agile-software-project-management#98]
# User Story 24
## Desc
As a lawyer 
I want a credits screen so that I know what sprites and other things that is created by others
## Acceptance criteria 
* A button that takes you to a screen that shows the assets we have used
### Tasks
- [x] Add "credits" button on home screen
- [x] Button should take you to a new page
- [x] Add assets to screen

## Estimate
