### ISSUE TITLE
User story 23: Facts Screen (in-game wiki)

### ISSUE THREAD

**Issue by Caramajau** [Oskmey/-Agile-software-project-management#99]
# User Story 23
## Desc
As an environmentalist gamer
I want a dedicated page for reading more about the trash
So that I can deepen my learning about them.
## Acceptance criteria 
There is a screen which can be accessed from the main menu displaying all facts about trash as well as providing all information about the sources. The page should be readable.
### Tasks
- [x] Create a new screen with textfields. 
- [x] The textfields can display facts about trash
- [x] Other textfields can display the sources
- [x] A new button from the main menu which leads to the new view
